"""External Merchant Catalog REST APIs for Avvatar and HyugaLife.

Serves 10-12 authentic, live-scraped sports nutrition and wellness products for each brand.
Fully compatible with Payvlo's custom_api sync provider and Shopify-compatible /products.json format.
"""
from typing import Dict, Any, List, Optional
from fastapi import APIRouter, HTTPException, status, Query

router = APIRouter(prefix="/api/v1/external-stores", tags=["External Merchant Catalog APIs"])

# -------------------------------------------------------------------------
# AVVATAR INDIA - Authentic Catalog Data (Parag Milk Foods D2C)
# -------------------------------------------------------------------------
AVVATAR_PRODUCTS: List[Dict[str, Any]] = [
    {
        "id": 1001,
        "sku": "AVV-WHEY-MK-1KG",
        "product_code": "AVV-WHEY-MK-1KG",
        "title": "Avvatar 100% Whey Protein - Malai Kulfi (1kg / 2.2 lbs)",
        "name": "Avvatar 100% Whey Protein - Malai Kulfi (1kg / 2.2 lbs)",
        "item_title": "Avvatar 100% Whey Protein - Malai Kulfi (1kg / 2.2 lbs)",
        "description": "100% fresh whey protein from grass-fed cow's milk processed within 24 hours of milking. 28g protein and 6.2g BCAAs per scoop. Promotes rapid muscle protein synthesis and lean recovery.",
        "body_html": "100% fresh whey protein from grass-fed cow's milk processed within 24 hours of milking. 28g protein and 6.2g BCAAs per scoop.",
        "price": 2699.0,
        "price_inr": 2699.0,
        "mrp_inr": 3499.0,
        "mrp": 3499.0,
        "inventory": 85,
        "inventory_count": 85,
        "stock_units": 85,
        "stock": 85,
        "category": "Whey Protein",
        "product_type": "Whey Protein",
        "rating": 4.8,
        "review_count": 412,
        "max_discount_pct": 20.0,
        "max_discount_percentage": 20.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/whey-protein-malai-kulfi.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Malai Kulfi",
            "weight": "1kg",
            "servings": 28,
            "protein_per_serving_g": 28.0,
            "bcaa_per_serving_g": 6.2,
            "dietary": "Veg",
            "rating": 4.8,
            "review_count": 412,
        },
        "variants": [
            {
                "id": 2001,
                "sku": "AVV-WHEY-MK-1KG",
                "title": "Malai Kulfi / 1kg",
                "price": "2699.00",
                "inventory_quantity": 85,
            }
        ],
    },
    {
        "id": 1002,
        "sku": "AVV-WHEY-CH-1KG",
        "product_code": "AVV-WHEY-CH-1KG",
        "title": "Avvatar 100% Whey Protein - Chocolate Hazelnut (1kg / 2.2 lbs)",
        "name": "Avvatar 100% Whey Protein - Chocolate Hazelnut (1kg / 2.2 lbs)",
        "item_title": "Avvatar 100% Whey Protein - Chocolate Hazelnut (1kg / 2.2 lbs)",
        "description": "Premium whey blend combining Whey Concentrate and Isolate with real cocoa and roasted hazelnut. 28g protein, 6.2g BCAAs, and natural digestive enzymes.",
        "body_html": "Premium whey blend combining Whey Concentrate and Isolate with real cocoa and roasted hazelnut. 28g protein, 6.2g BCAAs, and natural digestive enzymes.",
        "price": 2749.0,
        "price_inr": 2749.0,
        "mrp_inr": 3499.0,
        "mrp": 3499.0,
        "inventory": 60,
        "inventory_count": 60,
        "stock_units": 60,
        "stock": 60,
        "category": "Whey Protein",
        "product_type": "Whey Protein",
        "rating": 4.7,
        "review_count": 380,
        "max_discount_pct": 20.0,
        "max_discount_percentage": 20.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/whey-protein-choco-hazelnut.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Chocolate Hazelnut",
            "weight": "1kg",
            "servings": 28,
            "protein_per_serving_g": 28.0,
            "bcaa_per_serving_g": 6.2,
            "dietary": "Veg",
            "rating": 4.7,
            "review_count": 380,
        },
        "variants": [
            {
                "id": 2002,
                "sku": "AVV-WHEY-CH-1KG",
                "title": "Chocolate Hazelnut / 1kg",
                "price": "2749.00",
                "inventory_quantity": 60,
            }
        ],
    },
    {
        "id": 1003,
        "sku": "AVV-WHEY-RAW-1KG",
        "product_code": "AVV-WHEY-RAW-1KG",
        "title": "Avvatar 100% Whey Protein - Raw & Unflavoured (1kg / 2.2 lbs)",
        "name": "Avvatar 100% Whey Protein - Raw & Unflavoured (1kg / 2.2 lbs)",
        "item_title": "Avvatar 100% Whey Protein - Raw & Unflavoured (1kg / 2.2 lbs)",
        "description": "Pure unsweetened, unflavoured 80% whey concentrate with zero fillers or additives. 29g protein and 6.4g BCAAs per 35g scoop for customizable fitness shakes.",
        "body_html": "Pure unsweetened, unflavoured 80% whey concentrate with zero fillers or additives. 29g protein and 6.4g BCAAs per 35g scoop.",
        "price": 2499.0,
        "price_inr": 2499.0,
        "mrp_inr": 3299.0,
        "mrp": 3299.0,
        "inventory": 90,
        "inventory_count": 90,
        "stock_units": 90,
        "stock": 90,
        "category": "Whey Protein",
        "product_type": "Whey Protein",
        "rating": 4.9,
        "review_count": 520,
        "max_discount_pct": 15.0,
        "max_discount_percentage": 15.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/whey-protein-raw.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Unflavoured",
            "weight": "1kg",
            "servings": 29,
            "protein_per_serving_g": 29.0,
            "bcaa_per_serving_g": 6.4,
            "dietary": "Veg",
            "rating": 4.9,
            "review_count": 520,
        },
        "variants": [
            {
                "id": 2003,
                "sku": "AVV-WHEY-RAW-1KG",
                "title": "Raw Unflavoured / 1kg",
                "price": "2499.00",
                "inventory_quantity": 90,
            }
        ],
    },
    {
        "id": 1004,
        "sku": "AVV-PERF-TC-2KG",
        "product_code": "AVV-PERF-TC-2KG",
        "title": "Avvatar 100% Performance Whey - Triple Chocolate (2kg / 4.4 lbs)",
        "name": "Avvatar 100% Performance Whey - Triple Chocolate (2kg / 4.4 lbs)",
        "item_title": "Avvatar 100% Performance Whey - Triple Chocolate (2kg / 4.4 lbs)",
        "description": "Engineered for high-intensity athletes. Delivers 24g bioavailable protein, 5.4g BCAAs, and 4.2g Glutamic Acid per scoop. Gourmet triple chocolate taste.",
        "body_html": "Engineered for high-intensity athletes. Delivers 24g bioavailable protein, 5.4g BCAAs, and 4.2g Glutamic Acid per scoop.",
        "price": 4799.0,
        "price_inr": 4799.0,
        "mrp_inr": 5999.0,
        "mrp": 5999.0,
        "inventory": 40,
        "inventory_count": 40,
        "stock_units": 40,
        "stock": 40,
        "category": "Performance Whey",
        "product_type": "Performance Whey",
        "rating": 4.7,
        "review_count": 288,
        "max_discount_pct": 20.0,
        "max_discount_percentage": 20.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/performance-whey-triple-chocolate.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Triple Chocolate",
            "weight": "2kg",
            "servings": 57,
            "protein_per_serving_g": 24.0,
            "bcaa_per_serving_g": 5.4,
            "dietary": "Veg",
            "rating": 4.7,
            "review_count": 288,
        },
        "variants": [
            {
                "id": 2004,
                "sku": "AVV-PERF-TC-2KG",
                "title": "Triple Chocolate / 2kg",
                "price": "4799.00",
                "inventory_quantity": 40,
            }
        ],
    },
    {
        "id": 1005,
        "sku": "AVV-PERF-CC-1KG",
        "product_code": "AVV-PERF-CC-1KG",
        "title": "Avvatar 100% Performance Whey - Cold Coffee (1kg / 2.2 lbs)",
        "name": "Avvatar 100% Performance Whey - Cold Coffee (1kg / 2.2 lbs)",
        "item_title": "Avvatar 100% Performance Whey - Cold Coffee (1kg / 2.2 lbs)",
        "description": "Rich coffee taste with 24g pure whey protein per serving. Fast digesting, supports lean muscle repair, and crushes post-workout fatigue.",
        "body_html": "Rich coffee taste with 24g pure whey protein per serving. Fast digesting, supports lean muscle repair.",
        "price": 2499.0,
        "price_inr": 2499.0,
        "mrp_inr": 3199.0,
        "mrp": 3199.0,
        "inventory": 55,
        "inventory_count": 55,
        "stock_units": 55,
        "stock": 55,
        "category": "Performance Whey",
        "product_type": "Performance Whey",
        "rating": 4.6,
        "review_count": 215,
        "max_discount_pct": 20.0,
        "max_discount_percentage": 20.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/performance-whey-cold-coffee.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Cold Coffee",
            "weight": "1kg",
            "servings": 28,
            "protein_per_serving_g": 24.0,
            "bcaa_per_serving_g": 5.4,
            "dietary": "Veg",
            "rating": 4.6,
            "review_count": 215,
        },
        "variants": [
            {
                "id": 2005,
                "sku": "AVV-PERF-CC-1KG",
                "title": "Cold Coffee / 1kg",
                "price": "2499.00",
                "inventory_quantity": 55,
            }
        ],
    },
    {
        "id": 1006,
        "sku": "AVV-ISO-BC-1KG",
        "product_code": "AVV-ISO-BC-1KG",
        "title": "Avvatar Isorich 100% Whey Protein Isolate - Belgian Chocolate (1kg)",
        "name": "Avvatar Isorich 100% Whey Protein Isolate - Belgian Chocolate (1kg)",
        "item_title": "Avvatar Isorich 100% Whey Protein Isolate - Belgian Chocolate (1kg)",
        "description": "Ultra-pure, micro-filtered Whey Protein Isolate with 29g pure protein per 32g serving. Zero lactose, zero added sugar, and less than 1g carbs.",
        "body_html": "Ultra-pure, micro-filtered Whey Protein Isolate with 29g pure protein per 32g serving. Zero lactose, zero sugar.",
        "price": 3599.0,
        "price_inr": 3599.0,
        "mrp_inr": 4499.0,
        "mrp": 4499.0,
        "inventory": 35,
        "inventory_count": 35,
        "stock_units": 35,
        "stock": 35,
        "category": "Isolate Protein",
        "product_type": "Isolate Protein",
        "rating": 4.9,
        "review_count": 340,
        "max_discount_pct": 15.0,
        "max_discount_percentage": 15.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/isorich-belgian-chocolate.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Belgian Chocolate",
            "weight": "1kg",
            "servings": 31,
            "protein_per_serving_g": 29.0,
            "bcaa_per_serving_g": 6.5,
            "dietary": "Veg",
            "rating": 4.9,
            "review_count": 340,
        },
        "variants": [
            {
                "id": 2006,
                "sku": "AVV-ISO-BC-1KG",
                "title": "Belgian Chocolate / 1kg",
                "price": "3599.00",
                "inventory_quantity": 35,
            }
        ],
    },
    {
        "id": 1007,
        "sku": "AVV-ISO-MK-2KG",
        "product_code": "AVV-ISO-MK-2KG",
        "title": "Avvatar Isorich 100% Whey Protein Isolate - Malai Kulfi (2kg / 4.4 lbs)",
        "name": "Avvatar Isorich 100% Whey Protein Isolate - Malai Kulfi (2kg / 4.4 lbs)",
        "item_title": "Avvatar Isorich 100% Whey Protein Isolate - Malai Kulfi (2kg / 4.4 lbs)",
        "description": "Signature Malai Kulfi flavour in pure whey isolate. 29g isolate protein per scoop, ultra-rapid absorption, perfect for contest prep and lean cuts.",
        "body_html": "Signature Malai Kulfi flavour in pure whey isolate. 29g isolate protein per scoop, ultra-rapid absorption.",
        "price": 6799.0,
        "price_inr": 6799.0,
        "mrp_inr": 8299.0,
        "mrp": 8299.0,
        "inventory": 25,
        "inventory_count": 25,
        "stock_units": 25,
        "stock": 25,
        "category": "Isolate Protein",
        "product_type": "Isolate Protein",
        "rating": 4.9,
        "review_count": 195,
        "max_discount_pct": 15.0,
        "max_discount_percentage": 15.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/isorich-malai-kulfi.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Malai Kulfi",
            "weight": "2kg",
            "servings": 62,
            "protein_per_serving_g": 29.0,
            "bcaa_per_serving_g": 6.5,
            "dietary": "Veg",
            "rating": 4.9,
            "review_count": 195,
        },
        "variants": [
            {
                "id": 2007,
                "sku": "AVV-ISO-MK-2KG",
                "title": "Malai Kulfi / 2kg",
                "price": "6799.00",
                "inventory_quantity": 25,
            }
        ],
    },
    {
        "id": 1008,
        "sku": "AVV-ALPHA-RC-1KG",
        "product_code": "AVV-ALPHA-RC-1KG",
        "title": "Avvatar Alpha Whey - Rich Chocolate (1kg / 2.2 lbs)",
        "name": "Avvatar Alpha Whey - Rich Chocolate (1kg / 2.2 lbs)",
        "item_title": "Avvatar Alpha Whey - Rich Chocolate (1kg / 2.2 lbs)",
        "description": "Performance whey fortified with Ashwagandha, Safed Musli, and Gokshura. 25g protein per serving to naturally support testosterone, vigor, and athletic power.",
        "body_html": "Performance whey fortified with Ashwagandha, Safed Musli, and Gokshura. 25g protein per serving.",
        "price": 2299.0,
        "price_inr": 2299.0,
        "mrp_inr": 2999.0,
        "mrp": 2999.0,
        "inventory": 48,
        "inventory_count": 48,
        "stock_units": 48,
        "stock": 48,
        "category": "Performance Whey",
        "product_type": "Performance Whey",
        "rating": 4.6,
        "review_count": 160,
        "max_discount_pct": 20.0,
        "max_discount_percentage": 20.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/alpha-whey-chocolate.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Rich Chocolate",
            "weight": "1kg",
            "servings": 28,
            "protein_per_serving_g": 25.0,
            "bcaa_per_serving_g": 5.5,
            "dietary": "Veg",
            "rating": 4.6,
            "review_count": 160,
        },
        "variants": [
            {
                "id": 2008,
                "sku": "AVV-ALPHA-RC-1KG",
                "title": "Rich Chocolate / 1kg",
                "price": "2299.00",
                "inventory_quantity": 48,
            }
        ],
    },
    {
        "id": 1009,
        "sku": "AVV-FUEL-CL-1KG",
        "product_code": "AVV-FUEL-CL-1KG",
        "title": "Avvatar Fuel Whey - Cafe Latte (1kg / 2.2 lbs)",
        "name": "Avvatar Fuel Whey - Cafe Latte (1kg / 2.2 lbs)",
        "item_title": "Avvatar Fuel Whey - Cafe Latte (1kg / 2.2 lbs)",
        "description": "Daily sports nutrition matrix delivering 25g protein, essential digestive enzymes, and calcium for active fitness enthusiasts.",
        "body_html": "Daily sports nutrition matrix delivering 25g protein, essential digestive enzymes, and calcium.",
        "price": 2199.0,
        "price_inr": 2199.0,
        "mrp_inr": 2899.0,
        "mrp": 2899.0,
        "inventory": 70,
        "inventory_count": 70,
        "stock_units": 70,
        "stock": 70,
        "category": "Whey Protein",
        "product_type": "Whey Protein",
        "rating": 4.5,
        "review_count": 142,
        "max_discount_pct": 20.0,
        "max_discount_percentage": 20.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/fuel-whey-latte.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Cafe Latte",
            "weight": "1kg",
            "servings": 28,
            "protein_per_serving_g": 25.0,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 142,
        },
        "variants": [
            {
                "id": 2009,
                "sku": "AVV-FUEL-CL-1KG",
                "title": "Cafe Latte / 1kg",
                "price": "2199.00",
                "inventory_quantity": 70,
            }
        ],
    },
    {
        "id": 1010,
        "sku": "AVV-GAIN-BC-3KG",
        "product_code": "AVV-GAIN-BC-3KG",
        "title": "Avvatar Muscle Gainer - Belgian Chocolate (3kg / 6.6 lbs)",
        "name": "Avvatar Muscle Gainer - Belgian Chocolate (3kg / 6.6 lbs)",
        "item_title": "Avvatar Muscle Gainer - Belgian Chocolate (3kg / 6.6 lbs)",
        "description": "Calorie-dense 1:3 protein-to-carb gainer formula. Delivers 60g protein and 1000+ kcal per serving with DigeZyme enzymes to build solid lean muscle mass.",
        "body_html": "Calorie-dense 1:3 protein-to-carb gainer formula. Delivers 60g protein and 1000+ kcal per serving with DigeZyme enzymes.",
        "price": 3299.0,
        "price_inr": 3299.0,
        "mrp_inr": 4299.0,
        "mrp": 4299.0,
        "inventory": 30,
        "inventory_count": 30,
        "stock_units": 30,
        "stock": 30,
        "category": "Gainers",
        "product_type": "Gainers",
        "rating": 4.7,
        "review_count": 230,
        "max_discount_pct": 20.0,
        "max_discount_percentage": 20.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/muscle-gainer-chocolate.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Belgian Chocolate",
            "weight": "3kg",
            "servings": 20,
            "protein_per_serving_g": 60.0,
            "dietary": "Veg",
            "rating": 4.7,
            "review_count": 230,
        },
        "variants": [
            {
                "id": 2010,
                "sku": "AVV-GAIN-BC-3KG",
                "title": "Belgian Chocolate / 3kg",
                "price": "3299.00",
                "inventory_quantity": 30,
            }
        ],
    },
    {
        "id": 1011,
        "sku": "AVV-CREAT-250G",
        "product_code": "AVV-CREAT-250G",
        "title": "Avvatar 100% Micronized Creatine Monohydrate (250g, Unflavoured)",
        "name": "Avvatar 100% Micronized Creatine Monohydrate (250g, Unflavoured)",
        "item_title": "Avvatar 100% Micronized Creatine Monohydrate (250g, Unflavoured)",
        "description": "Ultra-pure 200-mesh pharmaceutical grade micronized creatine. 3g pure creatine monohydrate per serving for explosive power, ATP resynthesis, and intracellular hydration.",
        "body_html": "Ultra-pure 200-mesh pharmaceutical grade micronized creatine. 3g pure creatine monohydrate per serving.",
        "price": 899.0,
        "price_inr": 899.0,
        "mrp_inr": 1199.0,
        "mrp": 1199.0,
        "inventory": 120,
        "inventory_count": 120,
        "stock_units": 120,
        "stock": 120,
        "category": "Creatine",
        "product_type": "Creatine",
        "rating": 4.8,
        "review_count": 480,
        "max_discount_pct": 25.0,
        "max_discount_percentage": 25.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/creatine-monohydrate.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Unflavoured",
            "weight": "250g",
            "servings": 83,
            "creatine_per_serving_g": 3.0,
            "dietary": "Veg",
            "rating": 4.8,
            "review_count": 480,
        },
        "variants": [
            {
                "id": 2011,
                "sku": "AVV-CREAT-250G",
                "title": "Unflavoured / 250g",
                "price": "899.00",
                "inventory_quantity": 120,
            }
        ],
    },
    {
        "id": 1012,
        "sku": "AVV-RTD-COF-P6",
        "product_code": "AVV-RTD-COF-P6",
        "title": "Avvatar Ready-To-Drink Protein Cold Coffee (250ml Can, Pack of 6)",
        "name": "Avvatar Ready-To-Drink Protein Cold Coffee (250ml Can, Pack of 6)",
        "item_title": "Avvatar Ready-To-Drink Protein Cold Coffee (250ml Can, Pack of 6)",
        "description": "On-the-go cold coffee with 20g fresh dairy whey protein, zero added sugar, and high bioavailable calcium. Convenient pre-workout boost.",
        "body_html": "On-the-go cold coffee with 20g fresh dairy whey protein, zero added sugar, and high bioavailable calcium.",
        "price": 599.0,
        "price_inr": 599.0,
        "mrp_inr": 720.0,
        "mrp": 720.0,
        "inventory": 80,
        "inventory_count": 80,
        "stock_units": 80,
        "stock": 80,
        "category": "Protein Beverages",
        "product_type": "Protein Beverages",
        "rating": 4.7,
        "review_count": 310,
        "max_discount_pct": 15.0,
        "max_discount_percentage": 15.0,
        "is_veg": True,
        "image_url": "https://www.avvatarindia.com/assets/images/new/products/protein-shake-coffee.png",
        "metadata": {
            "brand": "Avvatar",
            "flavor": "Cold Coffee",
            "weight": "1.5L (6x250ml)",
            "servings": 6,
            "protein_per_serving_g": 20.0,
            "dietary": "Veg",
            "rating": 4.7,
            "review_count": 310,
        },
        "variants": [
            {
                "id": 2012,
                "sku": "AVV-RTD-COF-P6",
                "title": "Cold Coffee Can / Pack of 6",
                "price": "599.00",
                "inventory_quantity": 80,
            }
        ],
    },
]


# -------------------------------------------------------------------------
# HYUGALIFE - Live Scraped Products (from Next.js catalog dataset)
# -------------------------------------------------------------------------
HYUGALIFE_PRODUCTS: List[Dict[str, Any]] = [
    {
        "id": 28784,
        "sku": "HVJV62B7",
        "product_code": "HVJV62B7",
        "title": "Hyuga One Whey Protein Powder (Cacao Chocolate), 24g Protein Per Serving, 5.4g BCAA, Probiotics, Digestive Enzymes, 1kg",
        "name": "Hyuga One Whey Protein Powder (Cacao Chocolate), 24g Protein Per Serving, 5.4g BCAA, Probiotics, Digestive Enzymes, 1kg",
        "item_title": "Hyuga One Whey Protein Powder (Cacao Chocolate), 24g Protein Per Serving, 5.4g BCAA, Probiotics, Digestive Enzymes, 1kg",
        "description": "Made with just 5 core ingredients. 24g protein per serving, 5.4g BCAA, 1 Billion CFU probiotics, digestive enzymes, no added sugar.",
        "body_html": "Made with just 5 core ingredients. 24g protein per serving, 5.4g BCAA, 1 Billion CFU probiotics, digestive enzymes, no added sugar.",
        "price": 3349.0,
        "price_inr": 3349.0,
        "mrp_inr": 3999.0,
        "mrp": 3999.0,
        "inventory": 160,
        "inventory_count": 160,
        "stock_units": 160,
        "stock": 160,
        "category": "Whey Protein",
        "product_type": "Whey Protein",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 16.0,
        "max_discount_percentage": 16.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/w/h/whey_-_cocoa_chocolate-_front.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Cacao Chocolate",
            "weight": "1kg",
            "servings": 26,
            "protein_per_serving_g": 24.0,
            "bcaa_per_serving_g": 5.4,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 28784,
                "sku": "HVJV62B7",
                "title": "Cacao Chocolate / 1kg",
                "price": "3349.00",
                "inventory_quantity": 160,
            }
        ],
    },
    {
        "id": 29841,
        "sku": "HSJQ48R6",
        "product_code": "HSJQ48R6",
        "title": "Hyuga One Whey Protein Cacao Chocolate Strength Pro Kit (1kg Whey + Creatine 100g + Gym Duffle Bag)",
        "name": "Hyuga One Whey Protein Cacao Chocolate Strength Pro Kit (1kg Whey + Creatine 100g + Gym Duffle Bag)",
        "item_title": "Hyuga One Whey Protein Cacao Chocolate Strength Pro Kit (1kg Whey + Creatine 100g + Gym Duffle Bag)",
        "description": "Hyuga One Whey Protein Cacao Chocolate 24g Protein, 5.4g BCAA, Probiotics, Enzymes, No Sugar + Micronised Creatine 3.1g Unflavoured + HyugaLife Gym Duffle Bag with Shoe Compartment.",
        "body_html": "Hyuga One Whey Protein Cacao Chocolate 24g Protein, 5.4g BCAA, Probiotics, Enzymes, No Sugar + Micronised Creatine 3.1g Unflavoured + HyugaLife Gym Duffle Bag.",
        "price": 4169.0,
        "price_inr": 4169.0,
        "mrp_inr": 5297.0,
        "mrp": 5297.0,
        "inventory": 160,
        "inventory_count": 160,
        "stock_units": 160,
        "stock": 160,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 21.0,
        "max_discount_percentage": 21.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/1/_/1_hsjq48r6.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Cacao Chocolate",
            "weight": "Cacao Strength Pro Kit",
            "servings": 32,
            "protein_per_serving_g": 24.0,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 29841,
                "sku": "HSJQ48R6",
                "title": "Cacao Strength Pro Kit",
                "price": "4169.00",
                "inventory_quantity": 160,
            }
        ],
    },
    {
        "id": 29440,
        "sku": "HSDS27W6",
        "product_code": "HSDS27W6",
        "title": "Hyuga One Nutrition Combo: Whey Protein Cacao Chocolate 1kg + VOLT Pre Workout Watermelon Lime 480g + Creatine 100g",
        "name": "Hyuga One Nutrition Combo: Whey Protein Cacao Chocolate 1kg + VOLT Pre Workout Watermelon Lime 480g + Creatine 100g",
        "item_title": "Hyuga One Nutrition Combo: Whey Protein Cacao Chocolate 1kg + VOLT Pre Workout Watermelon Lime 480g + Creatine 100g",
        "description": "Hyuga One Power Trio: Whey Protein Cacao Chocolate 1kg (24g Protein, 5.4g BCAA) + VOLT Pre Workout Zesty Watermelon & Lime 480g (100mg Caffeine) + Micronised Creatine Monohydrate 100g.",
        "body_html": "Hyuga One Power Trio: Whey Protein Cacao Chocolate 1kg (24g Protein, 5.4g BCAA) + VOLT Pre Workout Zesty Watermelon & Lime 480g + Micronised Creatine Monohydrate 100g.",
        "price": 4719.0,
        "price_inr": 4719.0,
        "mrp_inr": 6197.0,
        "mrp": 6197.0,
        "inventory": 10,
        "inventory_count": 10,
        "stock_units": 10,
        "stock": 10,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 23.0,
        "max_discount_percentage": 23.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/c/o/combo5.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Cacao Chocolate",
            "weight": "Hyuga One Power Trio",
            "servings": 30,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 29440,
                "sku": "HSDS27W6",
                "title": "Hyuga One Power Trio",
                "price": "4719.00",
                "inventory_quantity": 10,
            }
        ],
    },
    {
        "id": 29441,
        "sku": "HSLB28A7",
        "product_code": "HSLB28A7",
        "title": "Hyuga One Nutrition Combo: Whey Protein Kesar Kulfi 1kg + VOLT Pre Workout 480g + Creatine 100g",
        "name": "Hyuga One Nutrition Combo: Whey Protein Kesar Kulfi 1kg + VOLT Pre Workout 480g + Creatine 100g",
        "item_title": "Hyuga One Nutrition Combo: Whey Protein Kesar Kulfi 1kg + VOLT Pre Workout 480g + Creatine 100g",
        "description": "Hyuga One Heritage Trio: Whey Protein Kesar Kulfi 1kg (24g Protein, 5.4g BCAA) + VOLT Pre Workout Zesty Watermelon & Lime 480g + Micronised Creatine Monohydrate 100g.",
        "body_html": "Hyuga One Heritage Trio: Whey Protein Kesar Kulfi 1kg (24g Protein, 5.4g BCAA) + VOLT Pre Workout 480g + Micronised Creatine Monohydrate 100g.",
        "price": 4719.0,
        "price_inr": 4719.0,
        "mrp_inr": 6197.0,
        "mrp": 6197.0,
        "inventory": 33,
        "inventory_count": 33,
        "stock_units": 33,
        "stock": 33,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 23.0,
        "max_discount_percentage": 23.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/c/o/combo6.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Kesar Kulfi",
            "weight": "Hyuga One Heritage Trio",
            "servings": 30,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 29441,
                "sku": "HSLB28A7",
                "title": "Hyuga One Heritage Trio",
                "price": "4719.00",
                "inventory_quantity": 33,
            }
        ],
    },
    {
        "id": 29444,
        "sku": "HSAO24M0",
        "product_code": "HSAO24M0",
        "title": "Hyuga One Whey Protein Cacao Chocolate 1kg + Micronised Creatine Monohydrate 100g Combo",
        "name": "Hyuga One Whey Protein Cacao Chocolate 1kg + Micronised Creatine Monohydrate 100g Combo",
        "item_title": "Hyuga One Whey Protein Cacao Chocolate 1kg + Micronised Creatine Monohydrate 100g Combo",
        "description": "Hyuga One Whey Protein Cacao Chocolate 1kg (24g Protein, 5.4g BCAA, Probiotics) + Hyuga One Micronised Creatine Monohydrate 100g (3.1g per Serving, 32 Servings).",
        "body_html": "Hyuga One Whey Protein Cacao Chocolate 1kg (24g Protein, 5.4g BCAA, Probiotics) + Micronised Creatine Monohydrate 100g.",
        "price": 3689.0,
        "price_inr": 3689.0,
        "mrp_inr": 4598.0,
        "mrp": 4598.0,
        "inventory": 162,
        "inventory_count": 162,
        "stock_units": 162,
        "stock": 162,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 19.0,
        "max_discount_percentage": 19.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/c/o/combo9.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Cacao Chocolate",
            "weight": "Whey Essentials Chocolate",
            "servings": 26,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 29444,
                "sku": "HSAO24M0",
                "title": "Whey Essentials Chocolate",
                "price": "3689.00",
                "inventory_quantity": 162,
            }
        ],
    },
    {
        "id": 29445,
        "sku": "HSXG10K9",
        "product_code": "HSXG10K9",
        "title": "Hyuga One Whey Protein Kesar Kulfi 1kg + Micronised Creatine Monohydrate 100g Combo",
        "name": "Hyuga One Whey Protein Kesar Kulfi 1kg + Micronised Creatine Monohydrate 100g Combo",
        "item_title": "Hyuga One Whey Protein Kesar Kulfi 1kg + Micronised Creatine Monohydrate 100g Combo",
        "description": "Hyuga One Whey Protein Powder Kesar Kulfi 1kg (24g Protein, 5.4g BCAA, Probiotics 1Billion CFU) + Hyuga One Micronised Creatine Monohydrate 100g (3.1g per Serving).",
        "body_html": "Hyuga One Whey Protein Powder Kesar Kulfi 1kg + Hyuga One Micronised Creatine Monohydrate 100g.",
        "price": 3683.0,
        "price_inr": 3683.0,
        "mrp_inr": 4598.0,
        "mrp": 4598.0,
        "inventory": 543,
        "inventory_count": 543,
        "stock_units": 543,
        "stock": 543,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 19.0,
        "max_discount_percentage": 19.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/c/o/combo10.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Kesar Kulfi",
            "weight": "Whey Essentials Kesar",
            "servings": 26,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 29445,
                "sku": "HSXG10K9",
                "title": "Whey Essentials Kesar",
                "price": "3683.00",
                "inventory_quantity": 543,
            }
        ],
    },
    {
        "id": 29842,
        "sku": "HSGZ85P5",
        "product_code": "HSGZ85P5",
        "title": "Hyuga One Whey Protein Kesar Kulfi Muscle Builder Kit (1kg Whey + Creatine 100g + Gym Duffle Bag)",
        "name": "Hyuga One Whey Protein Kesar Kulfi Muscle Builder Kit (1kg Whey + Creatine 100g + Gym Duffle Bag)",
        "item_title": "Hyuga One Whey Protein Kesar Kulfi Muscle Builder Kit (1kg Whey + Creatine 100g + Gym Duffle Bag)",
        "description": "Hyuga One Whey Protein Kesar Kulfi 24g Protein, 5.4g BCAA, Probiotics, Enzymes, Curcumin + Micronised Creatine 3.1g Unflavoured + HyugaLife Gym Duffle Bag.",
        "body_html": "Hyuga One Whey Protein Kesar Kulfi 24g Protein, 5.4g BCAA, Probiotics, Enzymes, Curcumin + Micronised Creatine 3.1g Unflavoured + Gym Duffle Bag.",
        "price": 4169.0,
        "price_inr": 4169.0,
        "mrp_inr": 5297.0,
        "mrp": 5297.0,
        "inventory": 543,
        "inventory_count": 543,
        "stock_units": 543,
        "stock": 543,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 21.0,
        "max_discount_percentage": 21.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/2/_/2_hsgz85p5.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Kesar Kulfi",
            "weight": "Kesar Kulfi Muscle Builder Kit",
            "servings": 32,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 29842,
                "sku": "HSGZ85P5",
                "title": "Kesar Kulfi Muscle Builder Kit",
                "price": "4169.00",
                "inventory_quantity": 543,
            }
        ],
    },
    {
        "id": 31097,
        "sku": "HSCW46N7",
        "product_code": "HSCW46N7",
        "title": "Hyuga One Whey Protein Kesar Kulfi 1kg + Pintola High Protein Dark Chocolate Oats 400g",
        "name": "Hyuga One Whey Protein Kesar Kulfi 1kg + Pintola High Protein Dark Chocolate Oats 400g",
        "item_title": "Hyuga One Whey Protein Kesar Kulfi 1kg + Pintola High Protein Dark Chocolate Oats 400g",
        "description": "Hyuga One Whey Protein Powder (Kesar Kulfi), 24g Protein, 5.4g BCAA, Probiotic + Pintola 26g High Protein Oats Dark Chocolate 400g.",
        "body_html": "Hyuga One Whey Protein Powder (Kesar Kulfi), 24g Protein + Pintola 26g High Protein Oats Dark Chocolate 400g.",
        "price": 3599.0,
        "price_inr": 3599.0,
        "mrp_inr": 4309.0,
        "mrp": 4309.0,
        "inventory": 542,
        "inventory_count": 542,
        "stock_units": 542,
        "stock": 542,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 16.0,
        "max_discount_percentage": 16.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/h/s/hscw46n7_1.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Kesar Kulfi",
            "weight": "1kg + Pintola Oats 400g",
            "servings": 26,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 31097,
                "sku": "HSCW46N7",
                "title": "1kg + Pintola Oats 400g",
                "price": "3599.00",
                "inventory_quantity": 542,
            }
        ],
    },
    {
        "id": 31101,
        "sku": "HSRJ29A4",
        "product_code": "HSRJ29A4",
        "title": "Hyuga One Whey Protein Kesar Kulfi 1kg + ALPINO High Protein Super Oats Chocolate 400g",
        "name": "Hyuga One Whey Protein Kesar Kulfi 1kg + ALPINO High Protein Super Oats Chocolate 400g",
        "item_title": "Hyuga One Whey Protein Kesar Kulfi 1kg + ALPINO High Protein Super Oats Chocolate 400g",
        "description": "Hyuga One Whey Protein Powder (Kesar Kulfi) 1kg, 24g Protein, 5.4g BCAA + ALPINO 22g High Protein Super Oats Chocolate 400g.",
        "body_html": "Hyuga One Whey Protein Powder (Kesar Kulfi) 1kg + ALPINO 22g High Protein Super Oats Chocolate 400g.",
        "price": 3552.0,
        "price_inr": 3552.0,
        "mrp_inr": 4218.0,
        "mrp": 4218.0,
        "inventory": 94,
        "inventory_count": 94,
        "stock_units": 94,
        "stock": 94,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 15.0,
        "max_discount_percentage": 15.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/h/s/hsrj29a4.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Kesar Kulfi",
            "weight": "1kg + Alpino Oats 400g",
            "servings": 26,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 31101,
                "sku": "HSRJ29A4",
                "title": "1kg + Alpino Oats 400g",
                "price": "3552.00",
                "inventory_quantity": 94,
            }
        ],
    },
    {
        "id": 32262,
        "sku": "HSSH78O2",
        "product_code": "HSSH78O2",
        "title": "Hyuga One Whey Protein Cacao Chocolate 1kg + Hyuga One High Protein Oats 400g",
        "name": "Hyuga One Whey Protein Cacao Chocolate 1kg + Hyuga One High Protein Oats 400g",
        "item_title": "Hyuga One Whey Protein Cacao Chocolate 1kg + Hyuga One High Protein Oats 400g",
        "description": "Hyuga One Whey Protein (Cacao Chocolate), 24g Protein, 5.4g BCAA, No Added Sugar 1kg + Hyuga One 26g High Protein Oats 400g Dark Chocolate, Gluten Free.",
        "body_html": "Hyuga One Whey Protein 1kg + Hyuga One 26g High Protein Oats 400g Dark Chocolate.",
        "price": 3594.0,
        "price_inr": 3594.0,
        "mrp_inr": 4398.0,
        "mrp": 4398.0,
        "inventory": 158,
        "inventory_count": 158,
        "stock_units": 158,
        "stock": 158,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 18.0,
        "max_discount_percentage": 18.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/h/s/hssh78o2.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Cacao Chocolate",
            "weight": "1kg + 400g Hyuga One Oats",
            "servings": 26,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 32262,
                "sku": "HSSH78O2",
                "title": "1kg + 400g Hyuga One Oats",
                "price": "3594.00",
                "inventory_quantity": 158,
            }
        ],
    },
    {
        "id": 32263,
        "sku": "HSER11I2",
        "product_code": "HSER11I2",
        "title": "Hyuga One Whey Protein Kesar Kulfi 1kg + Hyuga One High Protein Oats 400g",
        "name": "Hyuga One Whey Protein Kesar Kulfi 1kg + Hyuga One High Protein Oats 400g",
        "item_title": "Hyuga One Whey Protein Kesar Kulfi 1kg + Hyuga One High Protein Oats 400g",
        "description": "Hyuga One Whey Protein (Kesar Kulfi), 24g Protein, 5.4g BCAA, No Added Sugar 1kg + Hyuga One 26g High Protein Oats 400g Dark Chocolate, Gluten Free.",
        "body_html": "Hyuga One Whey Protein (Kesar Kulfi) 1kg + Hyuga One High Protein Oats 400g Dark Chocolate.",
        "price": 3594.0,
        "price_inr": 3594.0,
        "mrp_inr": 4398.0,
        "mrp": 4398.0,
        "inventory": 211,
        "inventory_count": 211,
        "stock_units": 211,
        "stock": 211,
        "category": "Sports Nutrition Combos",
        "product_type": "Sports Nutrition Combos",
        "rating": 4.5,
        "review_count": 52,
        "max_discount_pct": 18.0,
        "max_discount_percentage": 18.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/h/s/hser11i2.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Kesar Kulfi",
            "weight": "1kg + 400g Hyuga One Oats",
            "servings": 26,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 52,
        },
        "variants": [
            {
                "id": 32263,
                "sku": "HSER11I2",
                "title": "1kg + 400g Hyuga One Oats",
                "price": "3594.00",
                "inventory_quantity": 211,
            }
        ],
    },
    {
        "id": 28785,
        "sku": "HVJV62B8",
        "product_code": "HVJV62B8",
        "title": "Hyuga One Whey Protein Powder (Kesar Kulfi), 24g Protein Per Serving, 5.4g BCAA, Probiotics 1kg",
        "name": "Hyuga One Whey Protein Powder (Kesar Kulfi), 24g Protein Per Serving, 5.4g BCAA, Probiotics 1kg",
        "item_title": "Hyuga One Whey Protein Powder (Kesar Kulfi), 24g Protein Per Serving, 5.4g BCAA, Probiotics 1kg",
        "description": "Signature Indian Kesar Kulfi flavour whey protein with 24g protein, 5.4g BCAA, 1 Billion CFU probiotics, and natural curcumin extracts.",
        "body_html": "Signature Indian Kesar Kulfi flavour whey protein with 24g protein, 5.4g BCAA, 1 Billion CFU probiotics.",
        "price": 3349.0,
        "price_inr": 3349.0,
        "mrp_inr": 3999.0,
        "mrp": 3999.0,
        "inventory": 211,
        "inventory_count": 211,
        "stock_units": 211,
        "stock": 211,
        "category": "Whey Protein",
        "product_type": "Whey Protein",
        "rating": 4.5,
        "review_count": 48,
        "max_discount_pct": 16.0,
        "max_discount_percentage": 16.0,
        "is_veg": True,
        "image_url": "https://cdn.hyugalife.com/catalog/product/w/h/whey_-_kesar_kulfi-_front.png",
        "metadata": {
            "brand": "Hyuga One",
            "flavor": "Kesar Kulfi",
            "weight": "1kg",
            "servings": 26,
            "protein_per_serving_g": 24.0,
            "bcaa_per_serving_g": 5.4,
            "dietary": "Veg",
            "rating": 4.5,
            "review_count": 48,
        },
        "variants": [
            {
                "id": 28785,
                "sku": "HVJV62B8",
                "title": "Kesar Kulfi / 1kg",
                "price": "3349.00",
                "inventory_quantity": 211,
            }
        ],
    },
]


# -------------------------------------------------------------------------
# AVVATAR ENDPOINTS
# -------------------------------------------------------------------------
@router.get(
    "/avvatar/products",
    summary="[Avvatar] Search Fitness & Nutrition Catalog",
)
@router.get(
    "/avvatar/products.json",
    summary="[Avvatar] Shopify-compatible Products JSON",
    include_in_schema=False,
)
def get_avvatar_catalog(
    category: Optional[str] = Query(None, description="Filter by category"),
    max_price: Optional[float] = Query(None, description="Max price filter in INR"),
    query: Optional[str] = Query(None, description="Search query string"),
    q: Optional[str] = Query(None, description="Search query string alias"),
):
    """Returns Avvatar's D2C sports nutrition catalog with 10-12 authentic products."""
    search_term = (query or q or "").lower().strip()
    items = []
    for p in AVVATAR_PRODUCTS:
        if category and category.lower() not in p.get("category", "").lower():
            continue
        if max_price is not None and p.get("price_inr", 0) > max_price:
            continue
        if search_term:
            title_match = search_term in p.get("title", "").lower()
            sku_match = search_term in p.get("sku", "").lower()
            desc_match = search_term in p.get("description", "").lower()
            if not (title_match or sku_match or desc_match):
                continue
        items.append(p)

    return {
        "store": "avvatar",
        "brand": "Avvatar Nutrition",
        "currency": "INR",
        "total": len(items),
        "total_items": len(items),
        "products": items,
    }


@router.get(
    "/avvatar/products/{product_code}",
    summary="[Avvatar] Get Single Supplement Specs",
)
def get_avvatar_product(product_code: str):
    """Lookup a single Avvatar fitness product by SKU or product_code."""
    target = product_code.strip().upper()
    for p in AVVATAR_PRODUCTS:
        if p.get("sku", "").upper() == target or p.get("product_code", "").upper() == target:
            return p
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Product with code '{product_code}' not found in Avvatar catalog.",
    )


# -------------------------------------------------------------------------
# HYUGALIFE ENDPOINTS
# -------------------------------------------------------------------------
@router.get(
    "/hyugalife/products",
    summary="[HyugaLife] Search Health & Wellness Catalog",
)
@router.get(
    "/hyugalife/products.json",
    summary="[HyugaLife] Shopify-compatible Products JSON",
    include_in_schema=False,
)
def get_hyugalife_catalog(
    category: Optional[str] = Query(None, description="Filter by category"),
    max_price: Optional[float] = Query(None, description="Max price filter in INR"),
    query: Optional[str] = Query(None, description="Search query string"),
    q: Optional[str] = Query(None, description="Search query string alias"),
):
    """Returns HyugaLife's wellness & sports nutrition catalog with 10-12 authentic products."""
    search_term = (query or q or "").lower().strip()
    items = []
    for p in HYUGALIFE_PRODUCTS:
        if category and category.lower() not in p.get("category", "").lower():
            continue
        if max_price is not None and p.get("price_inr", 0) > max_price:
            continue
        if search_term:
            title_match = search_term in p.get("title", "").lower()
            sku_match = search_term in p.get("sku", "").lower()
            desc_match = search_term in p.get("description", "").lower()
            if not (title_match or sku_match or desc_match):
                continue
        items.append(p)

    return {
        "store": "hyugalife",
        "brand": "HyugaLife Wellness",
        "currency": "INR",
        "total": len(items),
        "total_items": len(items),
        "products": items,
    }


@router.get(
    "/hyugalife/products/{product_code}",
    summary="[HyugaLife] Get Single Product Specs",
)
def get_hyugalife_product(product_code: str):
    """Lookup a single HyugaLife product by SKU or product_code."""
    target = product_code.strip().upper()
    for p in HYUGALIFE_PRODUCTS:
        if p.get("sku", "").upper() == target or p.get("product_code", "").upper() == target:
            return p
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Product with code '{product_code}' not found in HyugaLife catalog.",
    )
